// src/types/payment.ts

/**
 * Defines the structure for a Payment Method object as used by the frontend components.
 * * NOTE: This structure includes the 'id' field, which is generated by transforming 
 * the database's '_id' field within the data fetching hook (e.g., useProfile.tsx).
 */
export interface PaymentMethod {
    // CRITICAL: Frontend standard ID, derived from MongoDB's _id
    id: string; 

    // Fields relevant to card display and management
    card_last_four: string;
    card_type: 'Visa' | 'MasterCard' | 'Amex' | string; 
    expires_at: string; // Stored as ISO date string or similar
    is_default: boolean;

    // Optional fields from the backend model (if applicable)
    createdAt: string; 
    updatedAt: string;
    // Add any other relevant fields your component needs (e.g., card holder name, etc.)
}