// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opfkvdsrtrxycxevfkxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZmt2ZHNydHJ4eWN4ZXZma3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTc4NTYsImV4cCI6MjA3MDg5Mzg1Nn0.hU55KibBingTdd3HefU0zntTnxUo2FUxwL1yLGRx1hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});